version: "3.1"
services:

  mariadb:
    image: mariadb:10.1
    container_name: doodle-mariadb
    working_dir: /application
    volumes:
      - .:/application
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "8083:3306"

  front:
    image: nginx:1.15.5
    container_name: doodle-front
    volumes:
    - ./front/chat-client/dist/chat-client/:/usr/share/nginx/html
    ports:
    - "8086:80"

  webserver:
    image: doodle-server
    container_name: doodle-back
    working_dir: /application
    depends_on:
      - "mariadb"
    volumes:
      - .:/application
    ports:
      - "8080:8080"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
